[package]
name = "clap-verbosity-flag"
version = "0.2.0"
authors = ["Pascal Hertleif <killercup@gmail.com>"]
description = "Easily add a `--verbose` flag to CLIs using Structopt"
readme = "README.md"
license = "MIT OR Apache-2.0"
repository = "https://github.com/rust-clique/clap-verbosity-flag"

[dependencies]
log = "0.4.1"
env_logger = "0.5.10"
failure = "0.1.1"
structopt = "0.2.8"
serde = "1.0"
serde_derive = "1.0"
